=== Urielakerhub/xml-dtd-practica/Documentos/xml-dtd-practica/ejercicio3/matricula.dtd
<!ELEMENT matricula (personal, pago)>
<!ELEMENT personal (dni, nombre, titulacion, curso_academico, domicilios)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios (domicilio+)>
<!ELEMENT domicilio (calle, numero, ciudad)>
<!ATTLIST domicilio tipo (familiar|habitual) #REQUIRED>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pago (tipo_matricula)>
<!ELEMENT tipo_matricula (#PCDATA)>

=== Urielakerhub/xml-dtd-practica/Documentos/xml-dtd-practica/ejercicio3/matricula.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula SYSTEM "matricula.dtd">
<matricula>
    <personal>
        <dni>12345678A</dni>
        <nombre>Uriel López</nombre>
        <titulacion>Ingeniería en Sistemas</titulacion>
        <curso_academico>2026-2027</curso_academico>
        <domicilios>
            <domicilio tipo="familiar">
                <calle>Av. Reforma</calle>
                <numero>100</numero>
                <ciudad>Hermosillo</ciudad>
            </domicilio>
            <domicilio tipo="habitual">
                <calle>Calle Universidad</calle>
                <numero>25</numero>
                <ciudad>Hermosillo</ciudad>
            </domicilio>
        </domicilios>
    </personal>
    <pago>
        <tipo_matricula>Ordinaria</tipo_matricula>
    </pago>
</matricula>
